QUESTIONS = {
    "python": {
        "Infosys": [
            "Explain GIL in Python. What are its implications?",
            "What are decorators in Python? Provide an example.",
            "Explain `__init__`, `__str__`, `__repr__` methods in Python classes.",
            "What is the difference between `list`, `tuple`, `set`, and `dictionary`?",
            "How do you handle exceptions in Python?",
            "Explain generators and iterators in Python.",
            "What is the difference between `range()` and `xrange()` (in Python 2) or `range()` in Python 3?",
            "How does garbage collection work in Python?",
            "Explain the use of `*args` and `**kwargs`.",
            "What is a lambda function? When would you use it?",
            "Discuss your experience with Python libraries like Pandas, NumPy, Scikit-learn.",
            "Write a Python function to clean a given text string (e.g., remove special characters, convert to lowercase).",
        ],
        "Wipro": [
            "Explain GIL in Python. What are its implications?",
            "What are decorators in Python? Provide an example.",
            "Explain `__init__`, `__str__`, `__repr__` methods in Python classes.",
            "What is the difference between `list`, `tuple`, `set`, and `dictionary`?",
            "How do you handle exceptions in Python?",
            "Explain generators and iterators in Python.",
            "How does garbage collection work in Python?",
            "Explain the use of `*args` and `**kwargs`.",
            "What is a lambda function? When would you use it?",
            "Discuss your experience with Python libraries like Pandas, NumPy, Scikit-learn.",
            "Write a Python function to clean a given text string (e.g., remove special characters, convert to lowercase).",
        ],
        "TCS": [
            "Explain GIL in Python. What are its implications?",
            "What are decorators in Python? Provide an example.",
            "Explain `__init__`, `__str__`, `__repr__` methods in Python classes.",
            "What is the difference between `list`, `tuple`, `set`, and `dictionary`?",
            "How do you handle exceptions in Python?",
            "Explain generators and iterators in Python.",
            "How does garbage collection work in Python?",
            "Explain the use of `*args` and `**kwargs`.",
            "What is a lambda function? When would you use it?",
            "Discuss your experience with Python libraries like Pandas, NumPy, Scikit-learn.",
            "Write a Python function to clean a given text string (e.g., remove special characters, convert to lowercase).",
        ],
        "General": [
            "Explain GIL in Python. What are its implications?",
            "What are decorators in Python? Provide an example.",
            "Explain `__init__`, `__str__`, `__repr__` methods in Python classes.",
            "What is the difference between `list`, `tuple`, `set`, and `dictionary`?",
            "How do you handle exceptions in Python?",
            "Explain generators and iterators in Python.",
            "What is the difference between `range()` and `xrange()` (in Python 2) or `range()` in Python 3?",
            "How does garbage collection work in Python?",
            "Explain the use of `*args` and `**kwargs`.",
            "What is a lambda function? When would you use it?",
        ],
    },
    "sql": {
        "Infosys": [
            "Explain different types of JOINS (INNER, LEFT, RIGHT, FULL OUTER).",
            "What is a subquery? When would you use it?",
            "Explain `GROUP BY` and `HAVING` clauses.",
            "What are SQL constraints? Give examples.",
            "What is the difference between `DELETE` and `TRUNCATE`?",
            "How do you optimize a SQL query?",
            "Explain the concept of transactions and ACID properties in SQL.",
            "What are stored procedures and functions?",
            "Write a SQL query to find the second highest salary from a table.",
            "Write a SQL query to calculate the running total of sales for each product.",
            "How do you handle duplicate records in SQL?",
        ],
        "Wipro": [
            "Explain different types of JOINS (INNER, LEFT, RIGHT, FULL OUTER).",
            "What is a subquery? When would you use it?",
            "Explain `GROUP BY` and `HAVING` clauses.",
            "What are SQL constraints? Give examples.",
            "What is the difference between `DELETE` and `TRUNCATE`?",
            "How do you optimize a SQL query?",
            "Explain the concept of transactions and ACID properties in SQL.",
            "What are stored procedures and functions?",
            "Write a SQL query to find the second highest salary from a table.",
            "Write a SQL query to calculate the running total of sales for each product.",
            "How do you handle duplicate records in SQL?",
        ],
        "TCS": [
            "Explain different types of JOINS (INNER, LEFT, RIGHT, FULL OUTER).",
            "What is a subquery? When would you use it?",
            "Explain `GROUP BY` and `HAVING` clauses.",
            "What are SQL constraints? Give examples.",
            "What is the difference between `DELETE` and `TRUNCATE`?",
            "How do you optimize a SQL query?",
            "Explain the concept of transactions and ACID properties in SQL.",
            "What are stored procedures and functions?",
            "Write a SQL query to find the second highest salary from a table.",
            "Write a SQL query to calculate the running total of sales for each product.",
            "How do you handle duplicate records in SQL?",
        ],
        "General": [
            "Explain different types of JOINS (INNER, LEFT, RIGHT, FULL OUTER).",
            "What is a subquery? When would you use it?",
            "Explain `GROUP BY` and `HAVING` clauses.",
            "What are SQL constraints? Give examples.",
            "What is the difference between `DELETE` and `TRUNCATE`?",
            "How do you optimize a SQL query?",
            "Explain the concept of transactions and ACID properties in SQL.",
            "What are stored procedures and functions?",
            "Write a query to get the Nth highest salary.",
            "How do you handle duplicate records in SQL?",
        ],
    },
    "machine learning": {
        "Infosys": [
            "Explain the difference between supervised and unsupervised learning. Provide examples of algorithms for each.",
            "What is overfitting and underfitting in machine learning? How can you detect and mitigate them?",
            "Describe regularization techniques (L1 and L2). When would you use one over the other?",
            "Explain the concept of a confusion matrix, precision, recall, F1-score, and accuracy.",
            "What is a ROC curve and AUC? How do you interpret them?",
            "How does a Decision Tree work? What are its advantages and disadvantages?",
            "Explain the working of a Random Forest. How does it improve upon a single Decision Tree?",
            "What is Gradient Boosting? How does XGBoost, LightGBM, or CatBoost differ from traditional Gradient Boosting?",
            "Explain the Central Limit Theorem. Why is it important in statistics and data science?",
            "Describe p-value and confidence intervals.",
            "How do you handle missing values in a dataset? What are different imputation techniques?",
            "What is feature scaling? Explain standardization vs. normalization.",
            "How would you design an experiment to test the effectiveness of a new product feature (e.g., A/B testing)?",
            "What are eigenvectors and eigenvalues? How are they used in PCA?",
            "What are ensemble methods? Give examples.",
            "Explain different types of recommender systems (collaborative filtering, content-based).",
            "What are Generative Adversarial Networks (GANs)?",
            "Describe the concept of transfer learning.",
            "How do you evaluate a regression model (R-squared, RMSE, MAE)?",
            "What are the challenges of working with imbalanced datasets and how do you address them?",
            "Explain the concept of an MLOps pipeline.",
            "What is feature importance? How do you calculate it?",
            "Discuss the trade-offs between interpretability and model performance.",
        ],
        "Wipro": [
            "What are the assumptions of linear regression? How do you check them?",
            "Explain the bias-variance trade-off. How does it relate to model complexity?",
            "Describe the k-means clustering algorithm. How do you determine the optimal number of clusters?",
            "What is logistic regression? Is it a classification or regression algorithm?",
            "How do you evaluate a classification model (metrics other than accuracy)?",
            "What is cross-validation? Why is it important?",
            "Explain the concept of a neural network. What is an activation function?",
            "What is the difference between supervised, unsupervised, and reinforcement learning?",
            "How would you approach a problem of anomaly detection?",
            "Given a dataset, how would you decide which machine learning algorithm to use?",
            "Discuss different types of sampling techniques.",
            "How do you ensure the reproducibility of your data science work?",
            "Explain Hadoop/Spark in the context of big data.",
            "How do you handle imbalanced datasets?",
            "What are ensemble methods? Give examples.",
            "What are Generative Adversarial Networks (GANs)?",
            "Describe the concept of transfer learning.",
            "Explain the concept of an MLOps pipeline.",
            "What is feature importance? How do you calculate it?",
        ],
        "TCS": [
            "Explain the difference between a time series and a regular regression problem.",
            "What is ARIMA model? What are its components?",
            "How do you perform hypothesis testing? Explain Type I and Type II errors.",
            "Describe different types of recommender systems.",
            "What are some common challenges in deploying machine learning models to production?",
            "Explain the concept of Gradient Descent. What are its variants (Batch, Stochastic, Mini-batch)?",
            "How do you choose between different evaluation metrics for a given problem?",
            "What is Natural Language Processing (NLP)? Give examples of NLP tasks.",
            "Discuss the importance of feature engineering. Provide some techniques.",
            "How would you handle a dataset with many categorical variables?",
            "Explain PCA. What are its limitations?",
            "What is the difference between a validation set, test set, and training set?",
            "How do you deal with outliers in a dataset?",
            "What are Generative Adversarial Networks (GANs)?",
            "Describe the concept of transfer learning.",
            "Explain the concept of an MLOps pipeline.",
            "What is feature importance? How do you calculate it?",
            "Imagine you are given a dataset of customer transactions. How would you build a model to predict customer churn?",
        ],
        "General": [
            "Explain the difference between supervised and unsupervised learning. Provide examples of algorithms for each.",
            "What is overfitting and underfitting in machine learning? How can you detect and mitigate them?",
            "Describe regularization techniques (L1 and L2). When would you use one over the other?",
            "Explain the concept of a confusion matrix, precision, recall, F1-score, and accuracy.",
            "What is a ROC curve and AUC? How do you interpret them?",
            "How does a Decision Tree work? What are its advantages and disadvantages?",
            "Explain the working of a Random Forest. How does it improve upon a single Decision Tree?",
            "What is Gradient Boosting? How does XGBoost, LightGBM, or CatBoost differ from traditional Gradient Boosting?",
            "Explain the Central Limit Theorem. Why is it important in statistics and data science?",
            "Describe p-value and confidence intervals.",
            "How do you handle missing values in a dataset? What are different imputation techniques?",
            "What is feature scaling? Explain standardization vs. normalization.",
            "What are ensemble methods? Give examples.",
            "What are Generative Adversarial Networks (GANs)?",
            "Describe the concept of transfer learning.",
            "How do you evaluate a regression model (R-squared, RMSE, MAE)?",
            "What are the challenges of working with imbalanced datasets and how do you address them?",
        ],
    },
    "data science": {
        "Infosys": [
            "Explain the difference between supervised and unsupervised learning. Provide examples of algorithms for each.",
            "What is overfitting and underfitting in machine learning? How can you detect and mitigate them?",
            "Describe regularization techniques (L1 and L2). When would you use one over the other?",
            "Explain the concept of a confusion matrix, precision, recall, F1-score, and accuracy.",
            "What is a ROC curve and AUC? How do you interpret them?",
            "Explain the Central Limit Theorem. Why is it important in statistics and data science?",
            "Describe p-value and confidence intervals.",
            "How do you handle missing values in a dataset? What are different imputation techniques?",
            "What is feature scaling? Explain standardization vs. normalization.",
            "How would you design an experiment to test the effectiveness of a new product feature (e.g., A/B testing)?",
            "What are eigenvectors and eigenvalues? How are they used in PCA?",
            "Describe a data science project you've worked on. What was your role, what challenges did you face, and what was the outcome?",
            "How do you explain complex machine learning concepts to a non-technical audience?",
            "What are ensemble methods? Give examples.",
            "Explain different types of recommender systems.",
            "What is model deployment? What steps are involved?",
        ],
        "Wipro": [
            "What are the assumptions of linear regression? How do you check them?",
            "Explain the bias-variance trade-off.",
            "Describe the k-means clustering algorithm. How do you determine the optimal number of clusters?",
            "What is logistic regression? Is it a classification or regression algorithm?",
            "What is cross-validation? Why is it important?",
            "What is the difference between supervised, unsupervised, and reinforcement learning?",
            "How do you ensure the reproducibility of your data science work?",
            "Describe the steps involved in a typical data science project lifecycle.",
            "How do you stay updated with the latest trends and technologies in data science?",
            "Explain different types of recommender systems.",
            "How do you handle imbalanced datasets?",
        ],
        "TCS": [
            "Explain the difference between a time series and a regular regression problem.",
            "What is ARIMA model? What are its components?",
            "How do you perform hypothesis testing? Explain Type I and Type II errors.",
            "What are some common challenges in deploying ML models to production?",
            "What is Natural Language Processing (NLP)? Give examples of NLP tasks.",
            "Discuss the importance of feature engineering. Provide some techniques.",
            "Describe your experience with cloud platforms (AWS, Azure, GCP) for data science.",
            "What are ethical considerations in data science and AI?",
            "How do you explain the 'black box' nature of some ML models?",
            "Imagine you are given a dataset of customer transactions. How would you build a model to predict customer churn?",
        ],
        "General": [
            "Explain the difference between supervised and unsupervised learning.",
            "What is overfitting and underfitting? How can you detect and mitigate them?",
            "Explain the concept of a confusion matrix, precision, recall, F1-score, and accuracy.",
            "What is a ROC curve and AUC?",
            "How do you handle missing values in a dataset?",
            "What is feature scaling? Explain standardization vs. normalization.",
            "What are ensemble methods? Give examples.",
            "What are Generative Adversarial Networks (GANs)?",
            "Describe the concept of transfer learning.",
            "How do you evaluate a regression model (R-squared, RMSE, MAE)?",
            "What is model deployment? What steps are involved?",
        ],
    },
    "data analysis": {
        "Infosys": [
            "Describe the typical workflow of a data analysis project.",
            "How do you perform exploratory data analysis (EDA)? What tools do you use?",
            "What are common statistical tests used in data analysis (e.g., t-test, ANOVA, chi-square)?",
            "How do you identify and handle outliers in a dataset?",
            "Explain the concept of correlation vs. causation.",
            "What are different types of data visualizations, and when would you use each?",
            "How do you present your findings to a non-technical audience?",
            "What is data cleaning? What are common issues you encounter and how do you resolve them?",
            "Discuss ethical considerations in data analysis.",
            "How do you validate the insights derived from your analysis?",
        ],
        "Wipro": [
            "Describe the typical workflow of a data analysis project.",
            "How do you perform exploratory data analysis (EDA)? What tools do you use?",
            "What are common statistical tests used in data analysis (e.g., t-test, ANOVA, chi-square)?",
            "How do you identify and handle outliers in a dataset?",
            "Explain the concept of correlation vs. causation.",
            "What are different types of data visualizations, and when would you use each?",
            "How do you present your findings to a non-technical audience?",
            "What is data cleaning? What are common issues you encounter and how do you resolve them?",
            "Discuss ethical considerations in data analysis.",
            "How do you validate the insights derived from your analysis?",
        ],
        "TCS": [
            "Describe the typical workflow of a data analysis project.",
            "How do you perform exploratory data analysis (EDA)? What tools do you use?",
            "What are common statistical tests used in data analysis?",
            "How do you identify and handle outliers in a dataset?",
            "Explain the concept of correlation vs. causation.",
            "What are different types of data visualizations, and when would you use each?",
            "How do you present your findings to a non-technical audience?",
            "What is data cleaning? What are common issues you encounter?",
            "Discuss ethical considerations in data analysis.",
            "How do you validate the insights derived from your analysis?",
        ],
        "General": [
            "Describe the typical workflow of a data analysis project.",
            "How do you perform exploratory data analysis (EDA)? What tools do you use?",
            "What are common statistical tests used in data analysis?",
            "How do you identify and handle outliers in a dataset?",
            "Explain the concept of correlation vs. causation.",
            "What are different types of data visualizations, and when would you use each?",
            "How do you present your findings to a non-technical audience?",
            "What is data cleaning? What are common issues you encounter?",
            "Discuss ethical considerations in data analysis.",
            "How do you validate the insights derived from your analysis?",
        ],
    },
    "data engineering": {
        "Infosys": [
            "Explain the concept of ETL.",
            "Explain the difference between OLTP and OLAP.",
            "What are different data warehousing concepts (e.g., star schema, snowflake schema)?",
            "Describe the architecture of a data lake.",
            "What is the role of Apache Kafka in a data engineering pipeline?",
            "Explain ETL vs. ELT processes. When would you use each?",
            "How do you handle data quality issues in a data pipeline?",
            "What are different types of databases you have worked with (relational, NoSQL, column-oriented)?",
            "Describe how you would set up a data pipeline for real-time data processing.",
            "What are common tools and technologies used in data engineering (e.g., Airflow, Spark, Flink)?",
            "How do you ensure data security and privacy in data engineering workflows?",
        ],
        "Wipro": [
            "Explain the concept of ETL.",
            "Explain the difference between OLTP and OLAP.",
            "What are different data warehousing concepts (e.g., star schema, snowflake schema)?",
            "Describe the architecture of a data lake.",
            "What is the role of Apache Kafka in a data engineering pipeline?",
            "Explain ETL vs. ELT processes. When would you use each?",
            "How do you handle data quality issues in a data pipeline?",
            "What are different types of databases you have worked with?",
            "Describe how you would set up a data pipeline for real-time data processing.",
            "What are common tools and technologies used in data engineering?",
            "How do you ensure data security and privacy in data engineering workflows?",
        ],
        "TCS": [
            "Explain the concept of ETL.",
            "Explain the difference between OLTP and OLAP.",
            "What are different data warehousing concepts (e.g., star schema, snowflake schema)?",
            "Describe the architecture of a data lake.",
            "What is the role of Apache Kafka in a data engineering pipeline?",
            "Explain ETL vs. ELT processes. When would you use each?",
            "How do you handle data quality issues in a data pipeline?",
            "What are different types of databases you have worked with?",
            "Describe how you would set up a data pipeline for real-time data processing.",
            "What are common tools and technologies used in data engineering?",
            "How do you ensure data security and privacy in data engineering workflows?",
        ],
        "General": [
            "Explain the difference between OLTP and OLAP.",
            "What are different data warehousing concepts (e.g., star schema, snowflake schema)?",
            "Describe the architecture of a data lake.",
            "What is the role of Apache Kafka in a data engineering pipeline?",
            "Explain ETL vs. ELT processes. When would you use each?",
            "How do you handle data quality issues in a data pipeline?",
            "What are different types of databases you have worked with?",
            "Describe how you would set up a data pipeline for real-time data processing.",
            "What are common tools and technologies used in data engineering?",
            "How do you ensure data security and privacy in data engineering workflows?",
        ],
    },
    "behavioral": {
        "Infosys": [
            "Tell me about yourself.",
            "Why do you want to join Infosys?",
            "Where do you see yourself in 5 years?",
            "What are your strengths and weaknesses?",
            "Describe a challenging situation you faced and how you overcame it.",
            "How do you handle pressure/stress?",
            "Are you a team player? Give an example.",
            "How do you keep yourself updated with new technologies?",
            "What motivates you?",
            "Do you have any questions for us?",
            "Are you willing to relocate?",
            "Are you open to working in different shifts/on weekends?",
            "How do you handle conflicts within a team?",
            "Describe a time when you failed. What did you learn from it?",
            "What is your ideal work environment?",
        ],
        "Wipro": [
            "Tell me about yourself.",
            "Why do you want to join Wipro?",
            "Where do you see yourself in 5 years?",
            "What are your strengths and weaknesses?",
            "Describe a challenging situation you faced and how you overcame it.",
            "How do you handle pressure/stress?",
            "Are you a team player? Give an example.",
            "How do you keep yourself updated with new technologies?",
            "What motivates you?",
            "Do you have any questions for us?",
            "Are you willing to relocate?",
            "Are you open to working in different shifts/on weekends?",
            "How do you handle conflicts within a team?",
            "Describe a time when you failed. What did you learn from it?",
            "What is your ideal work environment?",
        ],
        "TCS": [
            "Tell me about yourself.",
            "Why do you want to join TCS?",
            "Where do you see yourself in 5 years?",
            "What are your strengths and weaknesses?",
            "Describe a challenging situation you faced and how you overcame it.",
            "How do you handle pressure/stress?",
            "Are you a team player? Give an example.",
            "How do you keep yourself updated with new technologies?",
            "What motivates you?",
            "Do you have any questions for us?",
            "Are you willing to relocate?",
            "Are you open to working in different shifts/on weekends?",
            "How do you handle conflicts within a team?",
            "Describe a time when you failed. What did you learn from it?",
            "What is your ideal work environment?",
        ],
        "General": [
            "Tell me about yourself.",
            "Where do you see yourself in 5 years?",
            "What are your strengths and weaknesses?",
            "Describe a challenging situation you faced and how you overcame it.",
            "How do you handle pressure/stress?",
            "Are you a team player? Give an example.",
            "How do you keep yourself updated with new technologies?",
            "What motivates you?",
            "Do you have any questions for us?",
            "Are you willing to relocate?",
            "Are you open to working in different shifts/on weekends?",
            "How do you handle conflicts within a team?",
            "Describe a time when you failed. What did you learn from it?",
            "What is your ideal work environment?",
        ],
    },
    "general technical": {
        "Infosys": [
            "Explain the concept of RESTful APIs.",
            "What is the difference between HTTP and HTTPS?",
            "Describe the SOLID principles of object-oriented design.",
            "What is version control? Which system do you prefer (Git, SVN, etc.) and why?",
            "Explain the basics of Git commands (clone, pull, push, commit, branch, merge).",
            "What is continuous integration/continuous deployment (CI/CD)?",
            "How do you ensure code quality in your projects?",
            "What is containerization? Explain Docker or Kubernetes if you have experience.",
            "Describe the concept of microservices architecture. What are its pros and cons?",
            "How do you approach debugging a problem in a complex system?",
            "What is unit testing? Why is it important?",
            "Explain polymorphism and inheritance with real-world examples.",
            "What is the purpose of an interface/abstract class?",
            "How would you design a system to handle a large number of concurrent users?",
            "What are design patterns? Give an example of one you have used.",
            "Explain the concept of cloud computing. What are IaaS, PaaS, and SaaS?",
            "What are your thoughts on Agile methodology?",
        ],
        "Wipro": [
            "Explain the concept of RESTful APIs.",
            "What is the difference between HTTP and HTTPS?",
            "Describe the SOLID principles of object-oriented design.",
            "What is version control? Which system do you prefer and why?",
            "Explain the basics of Git commands.",
            "What is continuous integration/continuous deployment (CI/CD)?",
            "How do you ensure code quality in your projects?",
            "What is containerization? Explain Docker or Kubernetes.",
            "Describe the concept of microservices architecture.",
            "How do you approach debugging a problem in a complex system?",
            "What is unit testing? Why is it important?",
            "Explain polymorphism and inheritance with real-world examples.",
            "What is the purpose of an interface/abstract class?",
            "How would you design a system to handle a large number of concurrent users?",
            "What are design patterns? Give an example.",
            "Explain the concept of cloud computing.",
            "What are your thoughts on Agile methodology?",
        ],
        "TCS": [
            "Explain the concept of RESTful APIs.",
            "What is the difference between HTTP and HTTPS?",
            "Describe the SOLID principles of object-oriented design.",
            "What is version control? Which system do you prefer and why?",
            "Explain the basics of Git commands.",
            "What is continuous integration/continuous deployment (CI/CD)?",
            "How do you ensure code quality in your projects?",
            "What is containerization? Explain Docker or Kubernetes.",
            "Describe the concept of microservices architecture.",
            "How do you approach debugging a problem in a complex system?",
            "What is unit testing? Why is it important?",
            "Explain polymorphism and inheritance with real-world examples.",
            "What is the purpose of an interface/abstract class?",
            "How would you design a system to handle a large number of concurrent users?",
            "What are design patterns? Give an example.",
            "Explain the concept of cloud computing.",
            "What are your thoughts on Agile methodology?",
        ],
        "General": [
            "Explain the concept of RESTful APIs.",
            "What is the difference between HTTP and HTTPS?",
            "Describe the SOLID principles of object-oriented design.",
            "What is version control? Which system do you prefer and why?",
            "Explain the basics of Git commands.",
            "What is continuous integration/continuous deployment (CI/CD)?",
            "How do you ensure code quality in your projects?",
            "What is containerization? Explain Docker or Kubernetes.",
            "Describe the concept of microservices architecture.",
            "How do you approach debugging a problem in a complex system?",
            "What is unit testing? Why is it important?",
            "Explain polymorphism and inheritance with real-world examples.",
            "What is the purpose of an interface/abstract class?",
            "How would you design a system to handle a large number of concurrent users?",
            "What are design patterns? Give an example.",
            "Explain the concept of cloud computing.",
            "What are your thoughts on Agile methodology?",
        ],
    },
}

SKILL_ALIASES = {
    "ml": "machine learning",
    "ds": "data science",
    "da": "data analysis",
    "de": "data engineering",
    "gt": "general technical",
    "tech": "general technical",
    "hr": "behavioral",
    "behaviour": "behavioral",
    "behaviour": "behavioral",
}

COMPANIES = ["Infosys", "Wipro", "TCS", "General"]

SKILL_DISPLAY_NAMES = {
    "python": "Python",
    "sql": "SQL",
    "machine learning": "Machine Learning",
    "data science": "Data Science",
    "data analysis": "Data Analysis",
    "data engineering": "Data Engineering",
    "behavioral": "Behavioral / HR",
    "general technical": "General Technical",
}

SKILL_ICONS = {
    "python": "🐍",
    "sql": "🗄️",
    "machine learning": "🤖",
    "data science": "📊",
    "data analysis": "🔍",
    "data engineering": "⚙️",
    "behavioral": "🧠",
    "general technical": "💻",
}
